21 define service interfaces
electron2302/continuous-time-tracking pull request #23
Opened 2021-02-03 17:53 UTC by walli545

Closes #21

2021-02-03 17:56 UTC, sschoetz approved these changes

2021-02-04 09:47 UTC, sschoetz commented on ctt-frontend/src/app/services/activity.service.ts
> +   * @param activity, the activity to create.
```suggestion
   * @param activity, the activity to delete.
```

2021-02-04 09:49 UTC, sschoetz commented on ctt-frontend/src/app/services/activity.service.ts
> +   * And filtilter the cativities relating to the category,
```suggestion
   * And filter the activities relating to the category, 
```

2021-02-04 09:50 UTC, sschoetz commented on ctt-frontend/src/app/services/activity.service.ts
> +   * If neighter from nor to is provided,
```suggestion
   * If neither from nor to is provided, 
```

2021-02-04 09:50 UTC, sschoetz commented on ctt-frontend/src/app/services/category.service.ts
> +   * Get an existing category ba an id.
```suggestion
   * Get an existing category by an id.
```

2021-02-04 09:52 UTC, sschoetz commented on ctt-frontend/src/app/services/statistics.service.ts
> +   * Get the categoryID to the absolute
```suggestion
   * Get the categoryID to the relative
```

2021-02-04 09:54 UTC, sschoetz requested changes
Please review suggestions.

2021-02-04 09:54 UTC, AndHager approved these changes

2021-02-04 09:58 UTC, electron2302 approved these changes

2021-02-04 11:08 UTC, electron2302 approved these changes

2021-02-04 11:08 UTC, merged