9 service authentication
electron2302/continuous-time-tracking pull request #29
Opened 2021-02-05 11:31 UTC by AndHager

Implementation of the AuthGuard, AuthService and the AuthenticationComponent
Closes: #9

2021-02-05 12:01 UTC, walli545 requested changes

2021-02-05 12:01 UTC, walli545 commented on ctt-frontend/src/app/services/auth.service.ts
> +  user: CognitoUserInterface | undefined;
Please make all properties private and provide `isSignedIn` via a method => Encapsulation
Also remove unused `title` as well.
`user` and `authState` can be reduced to local scope.

2021-02-05 12:01 UTC, walli545 commented on ctt-frontend/src/app/services/auth.service.ts
> +  username(): Observable<String> {
```suggestion
  usernameObservable(): Observable<String> {
```

2021-02-05 12:07 UTC, electron2302 commented
Pleas merge develop to add CI

2021-02-06 10:46 UTC, sschoetz approved these changes

2021-02-08 10:32 UTC, walli545 approved these changes

2021-02-08 10:32 UTC, merged