10 service category
electron2302/continuous-time-tracking pull request #33
Opened 2021-02-06 18:44 UTC by sschoetz

Implement category service. AWS Back-end requires login functionality to be merged first.

2021-02-07 11:30 UTC, walli545 requested changes
Looks good! Nice that you also included tests! Please look at my improvement suggestions. Also, I would wait to merge this until we can test the functionality when signed in.

2021-02-07 11:30 UTC, walli545 commented on ctt-frontend/src/app/services/aws-category.service.spec.ts
> +    TestBed.configureTestingModule({});
You can remove the `TestBed` setup from `beforeEach` and the `it should be created` test. Just create the `apiMock` and `sut` objects for each test in the `beforeEach` method manually and store them as global variables (like `service`).
Then you only have the `apiMock.configure(...)`  call in each test and you lose some lines in the test code.

2021-02-07 11:30 UTC, walli545 commented on ctt-frontend/src/app/services/aws-category.service.spec.ts
> +      expect(
Also the `expect(...)` wrapping around the `apiMock.verify(...)` call is redundant and can be removed. `verify` throws when no call is found and so the test fails.

2021-02-07 11:30 UTC, walli545 commented on ctt-frontend/src/app/services/aws-category.service.ts
> +      excludeFromStatistics: input.excludeFromStatistics.map((v) =>
Maybe add private methods `convertStatisticTypeToApiStatisticType()` and  `convertApiStatisticTypeToStatisticType()`

2021-02-07 11:30 UTC, walli545 commented on ctt-frontend/src/app/services/aws-category.service.ts
> +          name: result.name,
I think also private methods for converting an `Category` to an `ApiCategory` and the other way make sense.

2021-02-08 14:17 UTC, AndHager approved these changes

2021-02-08 14:29 UTC, walli545 approved these changes

2021-02-08 14:29 UTC, merged