36 gui account
electron2302/continuous-time-tracking pull request #48
Opened 2021-02-09 16:13 UTC by AndHager

Closes #36

2021-02-09 17:08 UTC, walli545 requested changes

2021-02-09 17:08 UTC, walli545 commented on ctt-frontend/src/app/components/account/account.component.ts
> +    console.log('username: ' + username);
```suggestion
```

2021-02-09 17:08 UTC, walli545 commented on ctt-frontend/src/app/components/account/account.component.ts
> +    console.log('email: ' + email);
```suggestion
```

2021-02-09 17:08 UTC, walli545 commented on ctt-frontend/src/app/components/account/account.component.ts
> +    console.log('isVerified: ' + isVerified);
```suggestion
```

2021-02-09 17:10 UTC, walli545 approved these changes

2021-02-09 22:24 UTC, electron2302 reviewed
What are the 192 changes in the schema for? are they on purpose?

2021-02-10 11:19 UTC, sschoetz approved these changes

2021-02-10 11:19 UTC, merged