Refactored Icon and structured the README.md
electron2302/continuous-time-tracking pull request #52
Opened 2021-02-10 11:34 UTC by AndHager

Closes #4.

2021-02-10 16:27 UTC, sschoetz commented on README.md
> +, in the ./ctt-frontend directory.
```suggestion
in the ./ctt-frontend directory.
```

2021-02-10 16:27 UTC, sschoetz commented on README.md
> +You can build and serve your local changes localy with:
```suggestion
You can build and serve your local changes locally by running:
```

2021-02-10 16:28 UTC, sschoetz commented on README.md
> +, in the ./ctt-frontend directory.
```suggestion
in the ./ctt-frontend directory.
```

2021-02-10 16:28 UTC, sschoetz commented on README.md
> +You can run the tests with:
```suggestion
You can run the tests by running:
```

2021-02-11 09:50 UTC, sschoetz commented on README.md
> +The Entripoint of the CTT is the login screen:
```suggestion
The Entrypoint of the CTT is the login screen:
```

2021-02-11 09:51 UTC, sschoetz commented on README.md
> +Once you signed up your self, you will receive a verification email.
```suggestion
Once you signed up, you will receive a verification email.
```

2021-02-11 09:52 UTC, sschoetz commented on README.md
> +At this screen you are promt to start a new activity.
```suggestion
At this screen you are prompted to start a new activity.
```

2021-02-11 09:52 UTC, sschoetz commented on README.md
> +By clicking on the hamburger menue on the left of the "Continuous Time Tracking" label you can toggle the side navigation bar:
```suggestion
By clicking on the hamburger menu on the left of the "Continuous Time Tracking" label you can toggle the side navigation bar:
```

2021-02-11 09:53 UTC, sschoetz commented on README.md
> +By clicking on the "History" you can view the history of the current day and step trugh the days:
```suggestion
By switching to the "History"-Tab you can view the history of the current day and step trough the days:
```

2021-02-11 09:54 UTC, sschoetz commented on README.md
> +Useful references and and documantations we used in our project:
```suggestion
Useful references and and documentations we used in our project:
```

2021-02-11 09:55 UTC, electron2302 approved these changes

2021-02-11 09:55 UTC, walli545 requested changes

2021-02-11 09:55 UTC, walli545 commented on README.md
> +The Entripoint of the CTT is the login screen:
```suggestion
The Entrypoint of CTT is the login screen:
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +Once you signed up your self, you will receive a verification email.
```suggestion
Once you signed up yourself, you will receive a verification email.
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +At this screen you are promt to start a new activity.
```suggestion
At this screen you are prompted to start a new activity.
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +By clicking on the hamburger menue on the left of the "Continuous Time Tracking" label you can toggle the side navigation bar:
```suggestion
By clicking on the hamburger menu on the left of the "Continuous Time Tracking" label you can toggle the side navigation bar:
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +By clicking on the "History" you can view the history of the current day and step trugh the days:
```suggestion
By clicking on the "History" you can view the history of the current day and step through the days:
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +We use the default ESLint angular configuration.
```suggestion
We use the default ESLint angular configuration for static code analysis.
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +Furthermore we use the default prettier configuration.
```suggestion
Furthermore we use the default prettier configuration to ensure a consistent code formatting within the project.
```

2021-02-11 09:55 UTC, walli545 commented on README.md
> +Useful references and and documantations we used in our project:
```suggestion
Useful references and documantations we used in our project:
```

2021-02-11 10:48 UTC, walli545 requested changes

2021-02-11 10:48 UTC, walli545 commented on README.md
> +Furthermore we use the default prettier configuration.
```suggestion
Furthermore we use the default prettier configuration to ensure a consistent code formatting within the project.
```

2021-02-11 10:49 UTC, walli545 approved these changes

2021-02-11 10:49 UTC, sschoetz approved these changes

2021-02-11 10:50 UTC, electron2302 approved these changes

2021-02-11 10:51 UTC, merged